{% set version = "1.4.1" %}

package:
  name: stanza
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/stanza/stanza-{{ version }}.tar.gz
  sha256: 60f3ca58501983dfce66112ec209d925ec297c9872dcbcc323da416138e359d9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - emoji
    - numpy
    - protobuf
    - python >=3.6
    # AttributeError: module 'torch.nn' has no attribute 'Mish'
    # - pytorch >=1.3.0
    - pytorch >=1.9.0
    - pytest
    - requests
    - six
    - tqdm
    # this is not pinned upstream, but has `pip check` issues with <3
    - transformers >=3

test:
  imports:
    - stanza
    - stanza.models
    # verify torch/transformers import API
    - stanza.models.common.bert_embedding
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stanfordnlp/stanza
  summary: A Python NLP Library for Many Human Languages, by the Stanford NLP Group
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://stanfordnlp.github.io/stanza

extra:
  recipe-maintainers:
    - FernandezMathieu
    - bollwyvl
